export class Constants {
    public static readonly i18nLabel = {
    jayWedsToral: 'jayWedsToral',
    omShreeGaneshayNamah: 'omShreeGaneshayNamah',
    mrDeepakAnd: 'mrDeepakAnd',
    mrsHeena: 'mrsHeena',
    requestYourGraciousPresence: 'requestYourGraciousPresence',
    jay: 'jay',
    with: 'with',
    toral: 'toral',
    modhukaNivasi: 'modhukaNivasi',
    daughterOfMrHarshad: 'daughterOfMrHarshad',
    mrsMamta: 'mrsMamta',
    inviteText: 'inviteText',
    meet: 'meet',
    the: 'the',
    brideAndGroom: 'brideAndGroom',
    toralIsCreative: 'toralIsCreative',
    aSimpleGirl: 'aSimpleGirl',
    chirpyHappyGoLucky: 'chirpyHappyGoLucky',
    withHerNature: 'withHerNature',
    jayIsCalm: 'jayIsCalm',
    talentedCoding: 'talentedCoding',
    deeplyFamilyOriented: 'deeplyFamilyOriented',
    handsomeCharmKindHeart: 'handsomeCharmKindHeart',
    aMessageFrom: 'aMessageFrom',
    beganWithTwoFamilies: 'beganWithTwoFamilies',
    withLoveBlessings: 'withLoveBlessings',
    withLove: 'withLove',
    jayAndToral: 'jayAndToral',
    lookingForward: 'lookingForward',
    onFriday: 'onFriday',
    venue: 'venue',
    damodarWadi: 'damodarWadi',
    ashokNagar: 'ashokNagar',
    timing: 'timing',
    timeOnwards: 'timeOnwards',
    clickForDirections: 'clickForDirections',
    thingsToKnow: 'thingsToKnow',
    toHelpYouAtEase: 'toHelpYouAtEase',
    hashtag: 'hashtag',
    whilePostingPhotos: 'whilePostingPhotos',
    hashtagValue: 'hashtagValue',
    ourFamiliesAreExcitedTo: 'ourFamiliesAreExcitedTo',
    shreeGaneshayNamah: 'shreeGaneshayNamah',
    jayShreeKrishna: 'jayShreeKrishna',
    shreePithadMaa: 'shreePithadMaa',
    riddhiSiddhiSahit: 'riddhiSiddhiSahit',
    sahkutumbPadharjo: 'sahkutumbPadharjo',
    manglikPrasango: 'manglikPrasango',
    savant208230AprNaRoj: 'savant208230AprNaRoj',
    randalMaaPooja: 'randalMaaPooja',
    ganeshSthapna: 'ganeshSthapna',
    mandapMuhrat: 'mandapMuhrat',
    svaruvhiPhojan: 'svaruvhiPhojan',
    mameru: 'mameru',
    haldiPithi: 'haldiPithi',
    sangeetSandhya: 'sangeetSandhya',
    shubhSthalSaiMandirHall: 'shubhSthalSaiMandirHall',
    mosalPaksh: 'mosalPaksh',
    natvarlal: 'natvarlal',
    svIlaBen: 'svIlaBen',
    savant1May: 'savant1May',
    jaanPrasthan: 'jaanPrasthan',
    hastMelap: 'hastMelap'
};
  public static readonly guj = 'guj';
  public static readonly allowedLangs = ['en', 'hin', this.guj];

}